In [4]:
#THIS IS NOT THE BEST SOLUTION FOR THE PROBLEM AS IT TAKES A LOT OF TIME, BUT IT IS A GOOD ONE FOR LITTLE n. (Use genetic or exact algorithms for larger n)

import numpy as np
def knight_update(n,board,x,y,sum,sol):
  """
  The worst time complexity is O(8**(n**2))
  ------------------------------------------
  n= number of squares for each row and column
  board = list of n lists with n elements each one
  x:position x
  y:position y
  sum: Variable to see the step we are in
  sol: vector with tuples that gives the position x, y and the step
  """
  if sum==n**2:
    return True
  if (x<0) or (x>=n) or (y<0) or (y>=n) or board[x][y] != '*': #We discard every possibility that surpases the board
    return False
  board[x][y] = sum
  
  for pos_x, pos_y in zip([-2,-2,-1,-1,1,1,2,2],[-1,2,-2,2,-2,2,-1,1]): 
    if knight_update(n,board,x+pos_x,y+pos_y,sum+1,sol):
      sol.append((x+pos_x,y+pos_y,sum+1))
      return True
  board[x][y]='*'




def knight_info(n):
  """
  Main function
  """
  board =[['*' for i in range(n)]for j in range(n)]
  print(f'{np.array(board)}\n')
  sol=[]
  knight_update(n,board,0,0,0,sol)
  for x,y,step in sol[::-1]: #Not necessary
    print(f"Move {step}: ({x},{y})")
  
  print(f'\n {np.array(board)}')

knight_info(5)

[['*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*']
 ['*' '*' '*' '*' '*']]

Move 1: (1,2)
Move 2: (0,4)
Move 3: (2,3)
Move 4: (1,1)
Move 5: (0,3)
Move 6: (2,4)
Move 7: (4,3)
Move 8: (3,1)
Move 9: (1,0)
Move 10: (0,2)
Move 11: (1,4)
Move 12: (2,2)
Move 13: (3,0)
Move 14: (4,2)
Move 15: (3,4)
Move 16: (1,3)
Move 17: (0,1)
Move 18: (2,0)
Move 19: (4,1)
Move 20: (3,3)
Move 21: (2,1)
Move 22: (4,0)
Move 23: (3,2)
Move 24: (4,4)
Move 25: (2,3)

 [[ 0 17 10  5  2]
 [ 9  4  1 16 11]
 [18 21 12  3  6]
 [13  8 23 20 15]
 [22 19 14  7 24]]
